# Quickstart docker-compose configuration
# Use this for quickly running Boxento with the pre-built image

services:
  boxento:
    image: ghcr.io/sushaantu/boxento:latest
    container_name: boxento
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - VITE_ALLOWED_HOSTS=${VITE_ALLOWED_HOSTS:-}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped 