# Development docker-compose configuration
# Use this for local development with live reloading.
# For production, use docker-compose.prod.yml

services:
  boxento-dev:
    # Use the base Bun image directly for development
    image: oven/bun:1
    working_dir: /app
    # Installs dependencies if needed and starts the dev server
    command: sh -c "apt-get update && apt-get install -y curl --no-install-recommends && rm -rf /var/lib/apt/lists/* && bun install && bun run dev --host"
    ports:
      - "5173:5173"
    volumes:
      # Mount your local source code into the container
      - .:/app
      # Exclude node_modules to use the ones installed inside the container
      # This avoids host/container OS conflicts, especially with native modules
      - /app/node_modules
    environment:
      # Ensure development mode is set for Vite
      - NODE_ENV=development
      # Allow setting custom allowed hosts through environment
      - VITE_ALLOWED_HOSTS=${VITE_ALLOWED_HOSTS:-}
      # Pass host env vars if needed, e.g., for Firebase config during dev
      # VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
    # Basic healthcheck (might be flaky until dev server is fully ready)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s # Give the dev server time to start
    restart: unless-stopped 