services:
  boxento:
    image: oven/bun:1
    working_dir: /app
    command: sh -c "bun install && bun run dev --host"
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped 